#nullable enable
using System;
using System.Collections.Generic;
using GregTechCEuTerraria.Api.Machine.Feature;
using GregTechCEuTerraria.Api.Machine.Trait;
using Terraria.Localization;

namespace GregTechCEuTerraria.TerrariaCompat.Machine;

// Resolves RecipeLogic waiting-reason ids (gtceu.recipe[_logic|_modifier].*)
// to localized text in Mods.GregTechCEuTerraria.RecipeStatus.* (generated by
// port-locale.py). Internal ids stay in gtceu.* (set by ActionResult.Fail in
// the Api layer, which can't depend on tML locale keys).
public static class RecipeStatusText
{
	private const string LocPrefix       = "Mods.GregTechCEuTerraria.RecipeStatus.";
	private const string ConditionPrefix = "gtceu.recipe.condition.";

	// Suffixes don't collide across the three prefixes - single table covers all.
	private static readonly string[] InternalPrefixes =
	{
		"gtceu.recipe_modifier.",
		"gtceu.recipe_logic.",
		"gtceu.recipe.",
	};

	public static string Resolve(string reasonKey)
	{
		// Condition failures carry the human-readable requirement after '|'
		// (RecipeLogic.CheckConditions).
		if (reasonKey.StartsWith(ConditionPrefix, StringComparison.Ordinal))
		{
			int sep = reasonKey.IndexOf('|');
			if (sep >= 0) return reasonKey[(sep + 1)..];
			string locKeyG = LocPrefix + "condition";
			string textG = Language.GetTextValue(locKeyG);
			return textG == locKeyG ? reasonKey : textG;
		}

		string suffix = reasonKey;
		foreach (var pfx in InternalPrefixes)
		{
			if (reasonKey.StartsWith(pfx, StringComparison.Ordinal))
			{
				suffix = reasonKey[pfx.Length..];
				break;
			}
		}

		string locKey = LocPrefix + suffix;
		string text = Language.GetTextValue(locKey);
		// tML returns the key itself when unregistered - fall back to raw id.
		return text == locKey ? reasonKey : text;
	}

	// Single source for the short status string - both world hover and in-UI
	// footer route here, so they can't disagree on the WAITING reason.
	public static string StatusLine(RecipeLogic? rl, string workingVerb = "Running")
	{
		if (rl is null) return "Idle";
		if (rl.IsWorking())
			return $"{workingVerb} {FormatProgressSeconds(rl.GetProgress(), rl.GetMaxProgress())}";
		if (rl.IsWaiting() && rl.GetWaitingReason() is { } reason)
			return $"Waiting: {Resolve(reason)}";
		if (rl.IsSuspend())
			return "Suspended";
		return "Idle";
	}

	// Tick unit is MC ticks (20 Hz). Output: "1.25 / 3.50s".
	public static string FormatProgressSeconds(int progressTicks, int maxTicks)
	{
		double cur = progressTicks / 20.0;
		double max = maxTicks      / 20.0;
		return $"{cur.ToString("0.00")} / {max.ToString("0.00")}s";
	}

	// GetUnformedReason() prefers live matcher state (server) and falls back to
	// the persisted snapshot on MP clients (matcher is server-only).
	public static string StatusLineForMulti(
		Multiblock.MultiblockControllerMachine controller,
		RecipeLogic? rl,
		string workingVerb = "Running")
	{
		if (!controller.IsFormed)
		{
			var reason = controller.GetUnformedReason();
			if (!string.IsNullOrEmpty(reason))
				return $"[c/FFAA44:Structure not formed:][c/FF8888: {reason}]";
			return "[c/FFAA44:Structure not formed]";
		}
		return StatusLine(rl, workingVerb);
	}

	// Port of RecipeLogic.getFancyTooltip's idle branch (the waiting branch is
	// already inline in StatusLine - duplicating would be noise). Dedupe needed
	// since failureReasons is per-recipe and reasons recur.
	public static void AppendFailureDetail(RecipeLogic? rl, List<string> lines)
	{
		if (rl is null || rl.GetStatus() != RecipeLogicStatus.IDLE) return;
		HashSet<string>? seen = null;
		foreach (var reason in rl.GetFailureReasons())
		{
			string text = Resolve(reason);
			seen ??= new HashSet<string>();
			if (seen.Add(text))
				lines.Add($"[c/FF8888:{text}]");
		}
	}
}
